### ISSUE TITLE
Implement can-symbol

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-symbol#1]
Related issues:

 - https://github.com/canjs/canjs/issues/2931 - can-operate
 - https://github.com/canjs/can-define/issues/63 - formalize .serialize(), .get(), etc
 - https://github.com/canjs/can-define/issues/126 - access keys on can-define
 - https://github.com/canjs/can-util/issues/103 - Use symbol instead of types

## Symbols (and corresponding expected value)

All CanJS symbols will be prefixed with `can.`

Type detection:
- __isMapLike__ `Boolean` - Item has values at keys
- __isListLike__ `Boolean` - Item has values at enumerated keys
- __isValueLike__ `Boolean` - Item has a single value
- __isFunctionLike__ `Boolean` - Item can be called with arguments
- __isConstructorLike__ `Boolean`

Shape detection:
- __getOwnKeyNames__ - How to get a list of all the keys on this object.  Returns an iterator. 
- __keyDescriptor__ - Returns information about this key.  Probably info beyond `Object.getPropertyDescriptor` would normally provide.  
- __getValueDescriptor__ - Returns information about the value contained in this observable.
- __iterator__ - Same as iterator
- __proto__

Get / Set:
- __getValue__
- __setValue__
- __getKeyValue__
- __setKeyValue__

Call:
- __call__
- __apply__
- __new__

Observe:
- __onValue__ `cb() -> valueIndex`
- __offValue__ `cb()`
- __onKeyValue__ `cb() -> valueIndex`
- __offKeyValue__ `cb() -> valueIndex`
- __keyDependencies__ - The observable dependencies of a property in a  map-like structure.
- __valueDependencies__ - The observable dependencies of a value-like structure.  

### `.for(key)`

```js
var canSymbol = require("can-symbol");

// env supports Symbols:
canSymbol('bar') //-> Symbol('bar')

// env doesn't support Symbols
// return can-symbol-bar to avoid conflicts
canSymbol('bar') //-> 'can-symbol-bar'
```

## Questions 

- How would promises and streams work?

**Comment by matthewp** [comment]
Symbol has two APIs: `Symbol('foo') !== Symbol('foo')` and `Symbol.for('foo') === `Symbol.for('foo')`. The latter is saved in an internal map so that each call gets the same symbol back. Will can-symbol have both of these as well?

**Comment by justinbmeyer** [comment]
@matthewp These are really only for "well known" symbols.  They are there primarily for `can-operate` to use.  It's to house "statefulness".  There can be only one version of these symbols for CanJS to work.

**Comment by matthewp** [comment]
We need private Symbols in can-zone.

**Comment by justinbmeyer** [comment]
Why?

**Comment by matthewp** [comment]
They are semi-private properties. They are unenumerable and can only be touched by outside code if they use Object.getOwnPropertySymbols and even then you can't get the string key used to make that symbol (so effectively you can't tell what a Symbol represents).

**Comment by matthewp** [comment]
One place where we use them is here: https://github.com/canjs/can-zone/blob/master/lib/zones/xhr.js#L21 to detect of an XHR request should come from the XHR_CACHE that is returned by server rendering.

**Comment by justinbmeyer** [comment]
This is going to change to a symbol polyfill that also includes the above registered symbols.
